services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service-3
    ports:
      - "5672:5672"   # Port AMQP
      - "15672:15672" # Interface Web
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: